const SECURITY_HEADERS={
  'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin',
  'X-Frame-Options':'SAMEORIGIN','Permissions-Policy':'geolocation=(), camera=(), microphone=()'
};
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');}
function safeUrl(v){try{const u=new URL(String(v||''));return ['https:','http:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
function fmt(v){return Number(v||0).toLocaleString('ja-JP');}
function money(v){if(v==null)return'—';const n=Number(v),a=Math.abs(n),s=n<0?'-':'';if(a>=1e12)return`${s}${(a/1e12).toLocaleString('ja-JP',{maximumFractionDigits:2})}兆円`;if(a>=1e8)return`${s}${(a/1e8).toLocaleString('ja-JP',{maximumFractionDigits:1})}億円`;if(a>=1e4)return`${s}${(a/1e4).toLocaleString('ja-JP',{maximumFractionDigits:0})}万円`;return`${n.toLocaleString('ja-JP')}円`;}
async function detailBucket(key){const hash=await crypto.subtle.digest('SHA-1',new TextEncoder().encode(key));return(new DataView(hash).getUint32(0,false)%64).toString(16).padStart(2,'0');}
async function loadEntity(context,corporateNumber){const bucket=await detailBucket(corporateNumber);const url=new URL(`/data/company-registry/details/${bucket}.json`,context.request.url);const res=await context.env.ASSETS.fetch(url);if(!res.ok)return null;const data=await res.json();return data?.c?.[corporateNumber]||null;}
async function loadProcurementRows(context,companyIds){const rows=[];for(const id of companyIds||[]){if(!/^co_[0-9a-f]{12}$/.test(id))continue;const bucket=id.slice(3,5).toLowerCase();const url=new URL(`/data/company-details/${bucket}.json`,context.request.url);const res=await context.env.ASSETS.fetch(url);if(!res.ok)continue;const data=await res.json();const item=data?.c?.[id];if(item?.[3])rows.push(...item[3]);}return rows.sort((a,b)=>String(b[0]||'').localeCompare(String(a[0]||'')));}
function address(entity){const n=entity.nta||{};return [n.prefecture,n.city,n.street].filter(Boolean).join('')||'—';}
function renderAgencyBars(rows){const map=new Map();for(const r of rows)map.set(r[1],(map.get(r[1])||0)+Number(r[4]||0));const top=[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8),max=Math.max(...top.map(([,v])=>v),1);return top.map(([name,value])=>`<div class="barrow"><div>${esc(name)}</div><div class="track"><div class="bar" style="width:${Math.max(2,value/max*100).toFixed(1)}%"></div></div><b>${esc(money(value))}</b></div>`).join('');}
function renderTable(rows){if(!rows.length)return'<div class="empty">金額を確認できる調達案件はありません。</div>';const visible=20,shown=rows.slice(0,60);const body=shown.map((r,i)=>`<tr${i>=visible?' hidden data-extra-row':''}><td>${esc(r[0]||'—')}</td><td>${esc(r[1]||'—')}</td><td class="title"><a href="${esc(safeUrl(r[3]))}" target="_blank" rel="noreferrer">${esc(r[2]||'—')}</a></td><td>${esc(money(r[4]))}</td></tr>`).join('');const more=shown.length>visible?`<button class="more-btn" type="button" data-show-more>さらに${shown.length-visible}件を表示</button>`:'';return`<div class="table-wrap"><table><thead><tr><th>落札日</th><th>発注機関</th><th>案件</th><th>金額</th></tr></thead><tbody>${body}</tbody></table></div>${more}`;}
function financeAmount(v,u){if(v==null)return'—';if(!u||u==='JPY')return money(v);if(u==='pure')return fmt(v);return `${fmt(v)} ${u}`;}
function pct(v){return v==null?'—':`${Number(v).toLocaleString('ja-JP',{maximumFractionDigits:2})}%`;}
function renderFinanceSummary(entity){const f=entity.finance,ps=f?.periods||[];if(!ps.length)return'<div class="finance-empty"><b>公開財務は未収録です</b><p>gBizINFO・決算公告など、公式に取得・検証できた情報だけを追加します。売上や利益を推測で補完しません。</p></div>';const a=f.analysis||{},latest=ps[0]||{},legacy=f.snapshotStatus==='legacy',sourceLabel=legacy?'旧gBizINFOスナップショット':'gBizINFO';return`<div class="finance-source ${legacy?'legacy':''}"><b>${esc(sourceLabel)} ${esc(f.sourceDate||'')}</b><span>${legacy?'最新データではありません。':'取得済み公開財務'}</span></div><div class="finance-kpis"><div><span>${esc(a.primaryRevenueLabel||'売上系指標')}</span><b>${esc(financeAmount(a.primaryRevenue,a.primaryRevenueUnit))}</b></div><div><span>当期純利益 / 損失</span><b>${esc(financeAmount(a.netIncomeLoss,a.netIncomeLossUnit))}</b></div><div><span>総資産</span><b>${esc(financeAmount(a.totalAssets,a.totalAssetsUnit))}</b></div><div><span>従業員数</span><b>${a.employees==null?'—':esc(fmt(a.employees))+'人'}</b></div></div><div class="ratio-strip"><div><span>自己資本比率</span><b>${esc(pct(a.equityRatioPct))}</b></div><div><span>純利益率</span><b>${esc(pct(a.netMarginPct))}</b></div><div><span>売上系 前期比</span><b>${esc(pct(a.revenueGrowthPct))}</b></div><div><span>ROA参考値</span><b>${esc(pct(a.roaEndAssetsPct))}</b></div></div><p class="finance-period">最新収録期：${esc(latest.fiscalYear||'期間記載なし')}</p>`;}
function renderFinanceHistory(entity){const f=entity.finance,ps=f?.periods||[];if(!ps.length)return'';const rows=ps.map((p,i)=>`<div class="fin-row"><div class="fin-order"><span>回次</span><b>${i===0?'最新期':`${i}期前`}</b></div><div><span>${esc(p.primaryRevenueLabel||'売上系')}</span><b>${esc(financeAmount(p.primaryRevenue,p.primaryRevenueUnit))}</b></div><div><span>経常利益 / 損失</span><b>${esc(financeAmount(p.ordinaryIncomeLoss,p.ordinaryIncomeLossUnit))}</b></div><div><span>純利益 / 損失</span><b>${esc(financeAmount(p.netIncomeLoss,p.netIncomeLossUnit))}</b></div><div><span>純資産</span><b>${esc(financeAmount(p.netAssets,p.netAssetsUnit))}</b></div><div><span>総資産</span><b>${esc(financeAmount(p.totalAssets,p.totalAssetsUnit))}</b></div></div>`).join('');const source=f.sourceUrl?`<a href="${esc(safeUrl(f.sourceUrl))}" target="_blank" rel="noreferrer">gBizINFO公式配布元</a>`:'gBizINFO';return`<section class="section card panel"><div class="section-head"><h2>財務推移</h2><p>${esc(f.sourceDate||'')}時点 · ${source}</p></div><div class="finance-history">${rows}</div><p class="finance-note">gBizINFOの「回次0」を最新期として表示しています。過去回次の年度をDATLUME側で推測して付与しません。ROAは最新期の純利益÷期末総資産による参考値です。</p></section>`;}
function render(entity,rows){const n=entity.nta||{},p=entity.procurement||{},canonical=`https://datlume.com/unlisted-companies/${entity.corporateNumber}/`;const description=entity.finance?.periods?.length?`${entity.name}の法人基本情報、公共調達の受注実績、gBizINFO収録の公開財務を確認できます。`:`${entity.name}の法人基本情報と公共調達の受注実績を、国税庁法人番号データとDATLUME公共調達データから確認できます。`;const aliases=(p.aliases||[]).filter(x=>x&&x!==entity.name);const avg=rows.length?p.awardTotal/rows.length:null;const title=`${entity.name}｜未上場企業・公共調達データ | DATLUME`;return`<!doctype html><html lang="ja"><head><link rel="icon" type="image/svg+xml" href="/favicon.svg"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><meta name="description" content="${esc(description)}"><link rel="canonical" href="${esc(canonical)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/unlisted-company.css"><title>${esc(title)}</title></head><body>
<header><div class="wrap"><nav><a class="brand" href="/"><img src="/favicon.svg" alt="" width="24" height="24"><span>DATLUME</span></a><div class="navlinks"><a href="/unlisted-companies/">未上場企業</a><a href="/listed-companies/">上場企業</a><a href="/procurement/">公共調達</a><a href="/about-data/">データについて</a></div></nav><div class="crumb"><a href="/unlisted-companies/">未上場企業</a> / 法人番号 ${esc(entity.corporateNumber)}</div><div class="hero"><div><div class="eyebrow">UNLISTED COMPANY</div><h1>${esc(entity.name)}</h1><p>${esc(n.prefecture||'所在地未確認')} ${esc(n.city||'')} · 法人番号 ${esc(entity.corporateNumber)}</p></div><div class="status">現存会社<br><span>上場除外確認済み</span></div></div></div></header>
<main class="wrap"><section class="stats"><div class="card stat"><span>確認できる受注額</span><b>${esc(money(p.awardTotal))}</b><small>金額確認済み案件の合計</small></div><div class="card stat"><span>公共調達実績</span><b>${esc(fmt(p.awardCount))}件</b><small>${esc(p.firstAwardDate||'—')}〜${esc(p.lastAwardDate||'—')}</small></div><div class="card stat"><span>金額確認済み</span><b>${esc(fmt(p.awardAmountCount))}件</b><small>単価契約などは総額に含めない</small></div><div class="card stat"><span>平均受注額</span><b>${esc(avg==null?'—':money(avg))}</b><small>金額確認済み案件ベース</small></div></section>
<section class="section two"><div class="card panel"><div class="section-head"><h2>法人基本情報</h2><p>国税庁 法人番号公表サイト</p></div><div class="facts"><div><span>法人番号</span><b>${esc(entity.corporateNumber)}</b></div><div><span>所在地</span><b>${esc(address(entity))}</b></div><div><span>法人番号指定日</span><b>${esc(n.assignmentDate||'—')}</b></div><div><span>最終更新日</span><b>${esc(n.updateDate||'—')}</b></div>${n.furigana?`<div><span>フリガナ</span><b>${esc(n.furigana)}</b></div>`:''}${aliases.length?`<div><span>調達データ上の名称</span><b>${esc(aliases.slice(0,4).join(' / '))}</b></div>`:''}</div></div><div class="card panel"><div class="section-head"><h2>財務データ</h2><p>${entity.finance?.periods?.length?`${esc(entity.finance.periods.length)}期収録`:`未収録`}</p></div>${renderFinanceSummary(entity)}</div></section>${renderFinanceHistory(entity)}
<section class="section card panel"><div class="section-head"><h2>主な発注機関</h2><p>金額確認済み案件を集計</p></div><div class="bars">${renderAgencyBars(rows)||'<div class="empty">金額を確認できる案件はありません。</div>'}</div></section>
<section class="section card panel"><div class="section-head"><h2>公共調達の案件</h2><p>最新60件まで表示</p></div>${renderTable(rows)}</section>
<section class="section card panel source"><div class="section-head"><h2>出典と判定方法</h2></div><p>法人基本情報は国税庁「法人番号公表サイト」の全国全件データを使用しています。未上場判定は、現存する会社形態（株式会社・有限会社・合名会社・合資会社・合同会社）に限定し、日本取引所グループの東証上場銘柄一覧と金融庁EDINETコードリストの上場区分を除外しています。</p><p>公共調達はJETRO / 調達ポータル（GEPS） / 各自治体の公式入札・契約情報をDATLUMEで正規化したものです。受注額は企業の売上高ではありません。金額を総額として確認できない単価契約等は受注額集計に含めません。</p></section>
</main><footer><div class="wrap">DATLUME · <a href="/unlisted-companies/">未上場企業一覧に戻る</a> · <a href="/about-data/">データについて</a> · <a href="/privacy/">プライバシーポリシー</a></div></footer><script>{const b=document.querySelector('[data-show-more]');b?.addEventListener('click',()=>{const rs=[...document.querySelectorAll('[data-extra-row]')],expanded=b.dataset.expanded==='1';rs.forEach(r=>r.hidden=expanded);b.dataset.expanded=expanded?'0':'1';b.textContent=expanded?'さらに'+rs.length+'件を表示':'20件に戻す'})}</script></body></html>`;}
async function handle(context,headOnly=false){const corporateNumber=String(context.params.corporateNumber||'');if(!/^\d{13}$/.test(corporateNumber))return new Response('Not Found',{status:404,headers:SECURITY_HEADERS});const entity=await loadEntity(context,corporateNumber);if(!entity||entity.unlistedEligible!==true)return new Response('Not Found',{status:404,headers:SECURITY_HEADERS});const rows=await loadProcurementRows(context,entity.procurement?.companyIds||[]);return new Response(headOnly?null:render(entity,rows),{status:200,headers:{...SECURITY_HEADERS,'Content-Type':'text/html; charset=utf-8','Cache-Control':'public, max-age=3600, stale-while-revalidate=86400'}});}
export function onRequestGet(context){return handle(context,false)}
export function onRequestHead(context){return handle(context,true)}
