import generatedSummary from './summary.json';

// Single source of truth generated by collector/collect_jetro.py.
// Keep pages on the exported snapshot so source counts and build timestamp
// cannot drift from the dashboard shards produced in the same export.
export default generatedSummary;
